#!/bin/sh

## INIT - DIFINE CLIENT SYSTEM NAMES
CONSUMER_SYSTEM_NAME="alpine1consumer"
PROVIDER_SYSTEM_NAME="alpine1provider"

## STEP 0 --- INITIALIZE DIRECTORIES
mkdir $CONSUMER_SYSTEM_NAME
mkdir $PROVIDER_SYSTEM_NAME

## STEP 1 --- REQUEST A CERTIFICATE FOR THE CONSUMER SYSTEM
$PWD/requestCertificate.sh $CONSUMER_SYSTEM_NAME  

## STEP 2 --- USE MANAGEMENT TOOL TO REGISTER SYSTEM 

## STEP 2 a --- GET NORMALIZED PUBLIC KEY 
## FOR AUTHINFO PARAM OF SYSTEM REGISTRATION
CONSUMER_AUTHINFO="$( cat $PWD/$CONSUMER_SYSTEM_NAME/$CONSUMER_SYSTEM_NAME.pub.authinfo)"

## STEP 2 b --- CALL MANAGEMENT TOOLS SYSTEM REGISTRATION
cd ./managementtool
$PWD/register_system.sh "${CONSUMER_SYSTEM_NAME}" "${CONSUMER_AUTHINFO}" 

