#!/bin/sh

## INIT - DIFINE CLIENT SYSTEM NAMES
CONSUMER_SYSTEM_NAME="alpine1consumer"
PROVIDER_SYSTEM_NAME="alpine1provider"

## STEP 0 --- initialize directories
mkdir $CONSUMER_SYSTEM_NAME
mkdir $PROVIDER_SYSTEM_NAME

## STEP 1 --- REQUEST A CERTIFICATE FOR THE CONSUMER SYSTEM
$PWD/requestCertificate.sh $CONSUMER_SYSTEM_NAME  


